import './styles.css';
import './css/normalize.scss'
import './css/inputAndSlider.scss';
import './css/degree.scss'
import './css/change_day.scss'
import './css/date.scss'
import './css/fiveday.scss';
import './css/favorite.scss';
import './components/changeDays';
import './components/rendering_degree';
import './components/date';
import './components/display_quotes';
import './components/makeHeaders';
import './components/5dayModule';
import './components/chart';
import './components/makeBackground';
import './components/favorite'
